name: Push to Notion
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git-notion
      - name: Run git-notion
        env:
          NOTION_TOKEN_V2: ${{ secrets.NOTION_TOKEN_V2 }}
          NOTION_ROOT_PAGE: https://www.notion.so/snowsoft/TopLevel-0b80a693bbf24c61be64c31a41ff2eb1
        run: |
          git-notion